name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 */6 * * *" # runs every 6 hours
  workflow_dispatch:       # allows manual trigger

jobs:
  update-readme-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate GitHub Stats
        uses: anuraghazra/github-readme-stats@master
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_1 }}
