name: Update README with GitHub Stats

on:
  schedule:
    - cron: "0 */12 * * *" # Runs every 12 hours (at 0:00, 12:00 UTC)
  workflow_dispatch:        # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate GitHub Stats
        run: |
          echo "![GitHub Stats](https://github-readme-stats.vercel.app/api?username=${{ github.repository_owner }}&count_private=true&show_icons=true&theme=dark)" > STATS.md
          echo "![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=${{ github.repository_owner }}&count_private=true&layout=compact&theme=dark)" >> STATS.md

      - name: Update README.md
        run: |
          sed -i '/<!--STATS-START-->/,<!--STATS-END-->/c\<!--STATS-START-->\n'"$(cat STATS.md)"'\n<!--STATS-END-->' README.md

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update README stats"
