name: Update README with GitHub Stats

on:
  schedule:
    - cron: "0 0,12 * * *" # Runs at 00:00 and 12:00 UTC every day
  workflow_dispatch:        # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate GitHub Stats
        run: |
          echo "![GitHub Stats](https://github-readme-stats.vercel.app/api?username=Dipanjan932000&count_private=true&show_icons=true&theme=dark&token=${{ secrets.GH_TOKEN }})" > STATS.md
          echo "![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=Dipanjan932000&count_private=true&layout=compact&theme=dark&token=${{ secrets.GH_TOKEN }})" > LANGS.md

      - name: Update stats in README
        run: |
          sed -i '/<!--STATS-START-->/,/<!--STATS-END-->/c\<!--STATS-START-->\n'"$(cat STATS.md)"'\n<!--STATS-END-->' README.md
          sed -i '/<!--LANGS-START-->/,/<!--LANGS-END-->/c\<!--LANGS-START-->\n'"$(cat LANGS.md)"'\n<!--LANGS-END-->' README.md

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update README stats"
